apiVersion: v2
name: clickhouse
description: Single-instance ClickHouse deployment using StatefulSet
type: application

# Версия чарта
version: 0.1.0

# Версия приложения (ClickHouse)
appVersion: "24.12"