apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clickhouse.fullname" . }}
  labels:
    app: {{ include "clickhouse.name" . }}
spec:
  replicas: 1   # Single-инсталляция базы данных
  selector:
    matchLabels:
      app: {{ include "clickhouse.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "clickhouse.name" . }}
    spec:
      containers:
        - name: clickhouse
          # Задаём образ и версию через параметры
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          # Порт HTTP API ClickHouse
          ports:
            - containerPort: 8123

          # Подключаем volume для персистентности данных
          volumeMounts:
            - name: clickhouse-storage
              mountPath: /var/lib/clickhouse

            # Пользовательские конфиги ClickHouse
            - name: users-config
              mountPath: /etc/clickhouse-server/users.d

      # Описываем доступные volumes
      volumes:
        # PVC для хранения данных
        - name: clickhouse-storage
          persistentVolumeClaim:
            claimName: {{ include "clickhouse.fullname" . }}-storage

        # ConfigMap с пользователями
        - name: users-config
          configMap:
            name: {{ include "clickhouse.fullname" . }}-users
