apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "clickhouse.fullname" . }}-storage
spec:
  accessModes:
    - ReadWriteOnce   # ClickHouse в single-инсталляции использует RWO
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  # Позволяет управлять StorageClass через параметры
  storageClassName: {{ .Values.storage.className | quote }}