apiVersion: v1
kind: Service
metadata:
  # Основной сервис для доступа к ClickHouse
  name: {{ include "clickhouse.fullname" . }}
spec:
  type: {{ .Values.service.type }}  # ClusterIP по умолчанию
  selector:
    app: {{ include "clickhouse.name" . }}
  ports:
    - name: http       # HTTP API
      port: {{ .Values.service.port }}
      targetPort: 8123
    - name: tcp        # Клиентский TCP порт
      port: 9000
      targetPort: 9000